### ISSUE TITLE
Unable to load covalent code editor getting "window.require.config is not a function" 

### ISSUE THREAD

**Issue by jcheung0** [Teradata/covalent-code-editor#14]
When I try to load the covalent code editor, it crashes during ngAfterViewInit because its trying to use the RequireJS amd loader hence this function

`(<any>window).require.config({ paths: { 'vs': 'assets/monaco/vs' } });`

```
@angular/cli 1.2.4
node 6.11.2
os darwin x64
@angular/animations 4.2.3
@angular/cdk 2.0.0-beta.8
@angular/common 4.2.3
@angular/compiler 4.2.3
@angular/compiler-cli 4.3.3
@angular/core 4.2.3
@angular/flex-layout 2.0.0-beta.8
@angular/forms 4.2.3
@angular/http 4.2.3
@angular/material 2.0.0-beta.8
@angular/platform-browser 4.2.3
@angular/platform-browser-dynamic 4.2.3
@angular/platform-server 4.3.3
@angular/router 4.2.3
@angular/tsc-wrapped 4.2.3
@angular/cli 1.2.4
```

**Comment by jeremysmartt** [comment]
Hello,

Are you trying to run it in Electron or the Browser?  I just tried this and it seems to work in both.  For Electron you can see it running here:
https://github.com/Teradata/covalent-electron

For the Browser you can see it running here:
https://teradata.github.io/covalent/#/components/code-editor

Do you have any more information, like the error that is thrown, browser/electron version, etc

**Comment by jcheung0** [comment]
I'm trying to run it inside the browser within mdDialog not sure if that really matters

**Comment by jeremysmartt** [comment]
Can you post an example of your code?

**Comment by jcheung0** [comment]
Template
` <div fxLayout="row"> 
            

             <td-code-editor style="height: 200px" theme="vs" flex automaticLayout language="html"></td-code-editor> 
            
            <div angular2-ace-editor class="editor" [text]="templateBody" [mode]="editorMode" [theme]="editorTheme" [options]="editorOptions" (textChanged)="onBodyChanged($event)" style="height:300px;width:750px"></div>

        </div>`


.angular-cli.json

```
 "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        { "glob": "**/*", "input": "../node_modules/monaco-editor/min", "output": "./assets/monaco/" },
      "favicon.ico",
      "assets"


      ],

```
dependencies

```
"dependencies": {
    "@angular/animations": "4.2.3",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "4.2.3",
    "@angular/compiler": "4.2.3",
    "@angular/compiler-cli": "^4.2.3",
    "@angular/core": "4.2.3",
    "@angular/flex-layout": "2.0.0-beta.8",
    "@angular/forms": "4.2.3",
    "@angular/http": "4.2.3",
    "@angular/material": "2.0.0-beta.8",
    "@angular/platform-browser": "4.2.3",
    "@angular/platform-browser-dynamic": "4.2.3",
    "@angular/platform-server": "^4.3.2",
    "@angular/router": "4.2.3",
    "@angular/tsc-wrapped": "4.2.3",
    "@covalent/code-editor": "1.0.0-alpha.6-8",
    "@covalent/core": "1.0.0-beta.6",
    "@covalent/http": "1.0.0-beta.6",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.1",
    "@swimlane/ngx-charts": "^5.0.0",
    "angular-in-memory-web-api": "0.1.17",
    "angular2-jwt": "^0.2.3",
    "angular2-signaturepad": "^2.2.1",
    "angular2-text-mask": "^4.1.0",
    "brace": "^0.8.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "immutable": "^3.8.1",
    "jquery": "^3.1.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "monaco-editor": "^0.9.0",
    "node-sass": "4.5.3",
    "owl.carousel": "^2.2.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.1.0",
    "sockjs-client": "1.1.1",
    "ts-helpers": "^1.1.2",
    "zone.js": "0.8.14"
  }
```

**Comment by jeremysmartt** [comment]
I was able to load up the editor with the same dependencies you have and using:
```
<td-code-editor style="height: 200px" theme="vs" flex automaticLayout language="html"></td-code-editor> 
```

![screen shot 2017-08-09 at 11 03 56 am](https://user-images.githubusercontent.com/10502797/29136584-8ed980b4-7cf2-11e7-99c1-8d8b6884969b.png)

What is the exact error trace you are seeing?  Also, what is the full html template you are using?

**Comment by jcheung0** [comment]
below is a screen of my error and I started adding that <td-code-editor> blocks everywhere and geting the same issue.

![screen shot 2017-08-10 at 3 02 44 pm](https://user-images.githubusercontent.com/234250/29194186-5e8cbe08-7ddd-11e7-8989-d6e55ad13c34.png)

**Comment by jeremysmartt** [comment]
I think you might have something else on the page that is conflicting.  I see that you have on your page `<div angular2-ace-editor` I don't know if that one is conflicting or not, or maybe something else.  Can you work backwards?  Meaning start with a very simple page with nothing but the `<td-code-editor style="height: 200px" theme="vs" flex automaticLayout language="html"></td-code-editor>` on it.   If that works then slowly start adding back in your other pieces one by one.  

Also if you can post more of what your template and ts file look like that would help and any other components that you might be using?

**Comment by edgrosso** [comment]
Same error here
EDIT:
I managed to solve it. You have to completely remove all references to ng2-ace in both package.json and angular-cli.json

**Comment by moorthi07** [comment]
@edgrosso  Thanks. Removing ace reference from angular-cli - fixed this error.
TypeError: window.require.config is not a function.
