### ISSUE TITLE
Styling the editor

### ISSUE THREAD

**Issue by denodaeus** [Teradata/covalent-code-editor#15]
How would I change the font size for the editor?  Is there a way (without defining a new monaco style) to programatically set properties on the editor instance?

I'd mainly be interested in stuff like what's here on constructing the editor instance:

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#fontsize

**Comment by jeremysmartt** [comment]
hello @denodaeus 

A PR is coming soon with the ability to set the IEditorOptions

**Comment by denodaeus** [comment]
Thanks!

**Comment by denodaeus** [comment]
Is there a nightly for this?  What's the easiest way to get this update installed?  Looks like the build doesn't puts stuff in deploy/something instead of dist, amongst other things.  Do you publish built tgz's somewhere?

Thanks,

**Comment by jeremysmartt** [comment]
@denodaeus Your changes are now in the latest npm release:
https://www.npmjs.com/package/@covalent/code-editor

Thanks!
