### ISSUE TITLE
Possible Feature request: Fullscreen mode

### ISSUE THREAD

**Issue by madmandrew** [Teradata/covalent-code-editor#20]
I'm transitioning from using code-mirror to the new covalent code editor.  It's very nice and much easier to play with in angular 2!

However one feature that's missing is fullscreen mode.  with codemirror when the editor is in focus and you press F11 it would make the editor fullscreen.

**Comment by viccsjain** [comment]
I have code ready for this.
I will push it soon.

**Comment by viccsjain** [comment]
Raised PR for same.

**Comment by jeremysmartt** [comment]
closed by: https://github.com/Teradata/covalent-code-editor/pull/38
