### ISSUE TITLE
Feature Request: expose internal editor instance

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent-code-editor#21]
We need a getter to expose the internal editor instance so we can call all the extra API methods like `getSelection` or add custom commands to it.

**Comment by viccsjain** [comment]
I have fix ready for this. Will be raising PR soon.

**Comment by viccsjain** [comment]
PR: https://github.com/Teradata/covalent-code-editor/pull/54

**Comment by jeremysmartt** [comment]
PR https://github.com/Teradata/covalent-code-editor/pull/54
Is now merged.  With this change you can access the internal editor directly to do whatever you want.  See an example here:
https://github.com/Teradata/covalent-code-editor/blob/develop/docs/API.md
