### ISSUE TITLE
monaco-editor's page scroll  is not  showing 

### ISSUE THREAD

**Issue by moorthi07** [Teradata/covalent-code-editor#23]
monaco-editor's page scroll - minimap  is not  showing  in the RHS top corner!
I think its available from .9.0 . you are using .8.0. 

[https://github.com/Microsoft/vscode/issues/4865](https://github.com/Microsoft/vscode/issues/4865)

**Comment by jeremysmartt** [comment]
Hello, yes we are on .8.0 but will be upgrading to latest soon.

**Comment by moorthi07** [comment]
You might want to change documentation and description that it will not support angular 4 and lower versions  . Because its a ng5 is a breaking version with md5
