### ISSUE TITLE
Error loading monaco-editor

### ISSUE THREAD

**Issue by mauringhio** [Teradata/covalent-code-editor#31]
Hi, I get the following error when the app tries loading the monaco-editor, it must be a problem in the way the monaco lib is loaded in MonacoEditorService :
Refused to execute script from '.../loader.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by jeremysmartt** [comment]
Hello, can you post a Stackblitz example of your code that is getting this error?

**Comment by mauringhio** [comment]
I found out that it's a problem with monaco-editor and webpack that cannot load it properly.
Do you know if there's a possible workaround for monaco-editor with webpack?

**Comment by remeezp** [comment]
Hi @mauringhio, have you found a fix for this issue?

**Comment by viccsjain** [comment]
@mauringhio this issue mostly comes when it is not able to find files at mentioned path.
If you can paste complete console log, then it will be helpful to debug.

**Comment by jeremysmartt** [comment]
No comments on issue in months, closing
