### ISSUE TITLE
How to register a new Language?

### ISSUE THREAD

**Issue by Stevertus** [Teradata/covalent-code-editor#37]
I´m looking for the intended way to integrate a new language.
I tried it through the editorInitialized event: `(editorInitialized)="test(editWindow)"`
And passed the component.
But when I call the registerLanguage function on that component with this config
```
{
  id: '...',
    monarchTokensProvider:  [
         ...
      ],

  customTheme : {
    id: '...',
    theme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
     ...
    ]
  }
},
completionItemProvider:  [
...
  ]
}

```
It stops showing the editor. Any Solutions?

**Comment by jeremysmartt** [comment]
Hello @Stevertus 

Here is an example of that being done:
https://github.com/Teradata/covalent-electron/blob/develop/src/app/components/home/home.component.ts#L28

This is running in Electron but it would be the same if you are running in the browser.  If you want to see it running then go here:
https://github.com/Teradata/covalent-electron
and clone the repo and run the few commands to get the example up and running.

**Comment by jeremysmartt** [comment]
Here it is running in action:

![registerlanguage](https://user-images.githubusercontent.com/10502797/40382450-5b0f0e5a-5db3-11e8-8544-6916cedb2ebb.gif)

**Comment by Stevertus** [comment]
Thanks, I do understand it now.
But what if I want the language changed on load? It is a bit anoying with a button

**Comment by jeremysmartt** [comment]
The drop down is just an example, you can use whatever UX makes sense for your scenario.
