### ISSUE TITLE
Is it possible to change options of the editor during code execution?

### ISSUE THREAD

**Issue by makdeniss** [Teradata/covalent-code-editor#40]
Hi.

I would like to change the readOnly property during the flow of my application. Is that possible? Or is that value set only during editor init? Thanks!

**Comment by jeremysmartt** [comment]
@makdeniss I have created a PR to allow you to change options after the editor is initialized:
#42

**Comment by makdeniss** [comment]
@jeremysmartt thanks! Waiting for this to get merged!
