### ISSUE TITLE
How to use registerLanguage function of TdCodeEditorComponent to add a new language 

### ISSUE THREAD

**Issue by jlgrau** [Teradata/covalent-code-editor#44]
Hello 
I would like to use the csharp language inside the code editor component howewer this language does not seem to be available by default when setting the language property.

So I would like to use the registerLanguage function to do it however I cannot find any samples on this.

There is a sample for Electron but this does not work when using the component inside a browser.

Thanks for your help

**Comment by jesusvallez** [comment]
+1

**Comment by jeremysmartt** [comment]
PR https://github.com/Teradata/covalent-code-editor/pull/54
Is now merged.  With this change you can access the internal editor directly to do whatever you want.  See an example here:
https://github.com/Teradata/covalent-code-editor/blob/develop/docs/API.md
