### ISSUE TITLE
TypeScript - how to get detected symbols in the editor?

### ISSUE THREAD

**Issue by maciej-tokarz** [Teradata/covalent-code-editor#47]
The context menu has the option "Go to the symbol ..." and show all parsed objects (class, interfaces, properties...). Is it possible to get a list of these symbols (objects)?

Maciej

**Comment by maciej-tokarz** [comment]
OK, I have in file: covalent-code-editor.js in the TdCodeEditorComponent.prototype.initMonaco object monaco and monaco.languages.typescript.getTypeScriptWorker().

M.

**Comment by jesusvallez** [comment]
@maciej-tokarz Could you write an example, please? I need write a new Theme but I don't know how I can init monaco before print it and I think you are getting mocano like I want it

**Comment by maciej-tokarz** [comment]
My code: 
```
export declare class TdCodeEditorComponent implements OnInit, AfterViewInit, ControlValueAccessor {
    public monaco;
...
TdCodeEditorComponent.prototype.initMonaco = function () {
        this.monaco = monaco;
...
  async getSymbols() {
    const modelUri = this.editor._editor.getModel().uri;
    const worker = await this.editor.monaco.languages.typescript.getTypeScriptWorker();
    const client = await worker(modelUri);
    const symbols = await client.getNavigationBarItems(modelUri.toString());
    return symbols;
  }
```

M.

**Comment by jesusvallez** [comment]
`error TS2341: Property 'initMonaco' is private and only accessible within class 'TdCodeEditorComponent'.`

mmmmmm

**Comment by maciej-tokarz** [comment]
My hobby project and monaco:

https://github.com/maciej-tokarz/ts-class-diagram/blob/eb9c96fb87b8ee8a5294814bcb251f89e5264822/src/code-editor/esm5/covalent-code-editor.js#L527

https://github.com/maciej-tokarz/ts-class-diagram/blob/eb9c96fb87b8ee8a5294814bcb251f89e5264822/src/app/components/code-editor/code-editor.component.ts#L35

M.

**Comment by jesusvallez** [comment]
wow amazing work! thank you so much :)
