### ISSUE TITLE
value and ngModel

### ISSUE THREAD

**Issue by vtsitlak** [Teradata/covalent-code-editor#5]
Hi, I have a problem when I am using td-code-editor inside a form, using "value" property the assigned text is displayed on editor but I can't save the changes.

```
<td-code-editor style="height: 200px"
            id="statement"
            placeholder="Statement"
            required
            [value]="query.statement"   
            name="statement"
            theme="vs"
            flex
            language="sql">
          </td-code-editor>
```
 Using ngModel I can't see the assigned text, but I can save anything new I type on the editor. 
```
<td-code-editor style="height: 200px"
            id="statement"
            placeholder="Statement"
            required
            [ngModel]="query.statement"   // or [(ngModel)]
            ngDefaultControl
            name="statement"
            theme="vs"
            flex
            language="sql">
          </td-code-editor>
```
I tried several ways to connect value with the ngModel or ngModel with $event, then I was able to display the assigned text and save the changes, but every time I am typing a character at the end or in the middle of a previous text, after the first character the input point is going automatically to the beginning of the text. Also tried to use the onEditorValueChange event without results. So how can I use the editor and save the changes? Thank you

**Comment by jeremysmartt** [comment]
Hello @vtsitlak 
I will have a PR coming soon with support for ngModel.

Thanks!
