### ISSUE TITLE
[Angular] Code disappears when editor has been loaded before

### ISSUE THREAD

**Issue by ciacka** [Teradata/covalent-code-editor#58]
I faced with a problem of disappearing code in the editor.

**First thing first:**
Editor package version: `2.0.2`
Angular version: `7.1.3`

**Editor component usage in my component**
```
<td-code-editor style="height: 400px;" theme="vs-dark" language="javascript" formControlName="script"></td-code-editor>
```
As you can see above I use reactive forms.

Form's data are set using `patchValue` method after they are retrieved from the API. It's done asynchronously.
```javascript
this._deviceApiService.fetchDeviceScriptById(scriptId)
  .subscribe((script: DeviceScript) => {
    this.script = script;
    this.form.patchValue(script);
  });
```

### Observations
This happens when editor has been loaded before already, e.g. you go from page A to editor page for the first time and it works. Also when you visit editor page directly from URL or refresh page it's working.
But when you go back to page A and then again to editor page, then issue with disappearing code happens.

If I delay patching form value, then it's working in both cases (switching between pages or accessing directly via URL).
```javascript
setTimeout(() => this.form.patchValue(script), 500);
```

**Comment by christianmemije** [comment]
This was due to a race condition that occurred in the value setter in which we had a timeout that set the `value` to an outdated value. 

https://github.com/Teradata/covalent-code-editor/blob/ab6925300a0e4cb549ebeb71212a7aa2233e4911/src/platform/code-editor/code-editor.component.ts#L135-L140

Fix is in PR #60
