### ISSUE TITLE
What is the difference between these two emitters?

### ISSUE THREAD

**Issue by jesusvallez** [Teradata/covalent-code-editor#59]
https://github.com/Teradata/covalent-code-editor/blob/ab6925300a0e4cb549ebeb71212a7aa2233e4911/src/platform/code-editor/code-editor.component.ts#L114

https://github.com/Teradata/covalent-code-editor/blob/ab6925300a0e4cb549ebeb71212a7aa2233e4911/src/platform/code-editor/code-editor.component.ts#L116

**Comment by jeremysmartt** [comment]
This project has moved to https://github.com/Teradata/covalent
