### ISSUE TITLE
Monaco-editor not the same version in app and package

### ISSUE THREAD

**Issue by abierbaum** [Teradata/covalent-code-editor#61]
I am likely missing something here, but when I install @covalent/code-editor it ends up using monaco-editor version 0.10.1.

This is because the version is specified in the npm module package.json file:
https://github.com/Teradata/covalent-code-editor/blob/develop/src/platform/code-editor/package.json#L40

The way it is specified should allow for using a more recent version of monaco, but I can't figure out how to override this to get the most recent version.  Looking in the repository, it looks like the repo expects that people should or could use the most recent version: https://github.com/Teradata/covalent-code-editor/blob/develop/package.json#L71

Is this a simple oversight that the src/platform/code-editor/package.json file isn't updated or is this by design and if so, how can I override it.

Sorry for the newbie question.

**Comment by abierbaum** [comment]
One more data point which seems confusing to me but may clarify some things.  When I look at the bundled monaco editor files in:  @covalent/code-editor/assets/monaco/vs/editor/editor.main.js  I see:

```
/*!-----------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Version: 0.15.5(3d42593a5844407ab71d47b348ea3a8de5fec848)
 * Released under the MIT license
 * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
 *-----------------------------------------------------------*/
(function(){
```
Which makes me think that version 0.15.5 of the monaco editor is bundled with the npm package.  But that doesn't match the version in the package.json file of the base repo (0.15.6) or the version in the src/platfomr/code-editor/package.json (^0.10.1).

**Comment by viccsjain** [comment]
This seems to be problem with monaco-editor bundling.
If you install monaco-editor@0.15.6, It will show following version in monaco-editor/monaco.d.ts:

```
/*!-----------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Type definitions for monaco-editor v0.15.6
 * Released under the MIT license
*-----------------------------------------------------------*/
```

But at the same time if you go to monaco-editor/min/editor/editor.main.js
```
/*!-----------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Version: 0.15.5(3d42593a5844407ab71d47b348ea3a8de5fec848)
 * Released under the MIT license
 * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
 *-----------------------------------------------------------*/
```
It shows the same information which you mentioned.
So it does not seem to be problem with covalent-code-editor.

**Comment by emoralesb05** [comment]
Yes, we bundle a monaco version out of easiness, but you can override this by replacing which assets get loaded. 

Just make sure your angular.json points to `node_modules/monaco-editor/min` instead of `node_modules/@covalent/code-editor/assets/monaco`

We might make this a requirement going forward, so we might deprecate the bundled version.

Edit: Real sorry for the late response.

**Comment by emoralesb05** [comment]
You can reference this PR to see what i mean

https://github.com/Teradata/covalent-code-editor/pull/69
