### ISSUE TITLE
Incorrect types for editorProxy

### ISSUE THREAD

**Issue by abierbaum** [Teradata/covalent-code-editor#62]
I have covalent-code-editor working great.  Thanks for the wonderful project.

But now I am trying to add a callback to the CodeEditor object so I know when the cursor position changes.

I tried something like this:

```
   onCfgEditorInit(editor: monaco.editor.ICodeEditor): void {
      console.log('editor initialized: ', editor);      

      const handler = editor.onDidChangeCursorPosition((e) => {
         console.log('Cursor pos changed: ', e);
         const model = editor!.getModel();
         if (model != null) {
            const offset = model.getOffsetAt(e.position);
            console.log('offset: ', offset);
         }
      });
   }
```

It didn't work though because it said that model.getModel was not a function.  After looking in the debugger I found that it is actually a Promise.

After a little debugging I found this is because the object passed to `onEditorInitialized` is not an ICodeEditor, but is instead a Proxy wrapping an ICodeEditor and turning all calls into async calls that return a promise.  [1] [2]

It looks like this is so the code can handle the case of an embedded electron editor.  I am just in a browser so this doesn't matter as much to me, but I get the idea.  But it does cause a problem because it means all the types in the code are off because the interfaces like ICodeEditor don't know that the methods now return Promise's instead of the normal types.

Am I missing something?  Are there a set of types can can be used to handle this or is there a way in my case to simply get access to the base editor directly?  (note: I understand I would need to call ChangeDetectorRef.detectChanges() on my own, but I can work with that)

1: https://github.com/Teradata/covalent-code-editor/blob/develop/src/platform/code-editor/code-editor.component.ts#L830
2: https://github.com/Teradata/covalent-code-editor/blob/develop/src/platform/code-editor/code-editor.component.ts#L782

**Comment by jeremysmartt** [comment]
Hello, to get at the editor Instance please see the example listed at the bottom of the page here:
https://github.com/Teradata/covalent-code-editor/blob/develop/docs/API.md

Notice the use of async/await

**Comment by abierbaum** [comment]
Having to cast the line to `any` is the part that seems off to me.  We lose all the type information.  I understand the reasoning, just hoping there was another way.

```
async onEditorInitialized(editor: any): Promise<void> {
    let line: any = await editor.getPosition();

    this.column = line.column;
    this.lineNumber = line.lineNumber;
  }
}
```

For now what I ended up doing since I am using a browser deployment is using ViewChild to get the component and then grabbing the private _editor off of it directly and cast that to `monaco.editor.ICodeEditor`.  That leaves me with type-safety but is definitely a hack.
